---
- hosts: init_pis
  become: yes
  roles:
    - config

- hosts: k3s_cluster
  become: yes
  vars:
    tailscale_oauth_key: "{{ lookup('env', 'TAILSCALE_OAUTH_KEY') }}"
  roles:
    - role: artis3n.tailscale
      vars:
        verbose: true
        tailscale_authkey: "{{ tailscale_oauth_key }}"
        tailscale_tags: ["jarvis-cluster"]

- hosts: k3s_cluster
  become: yes
  vars:
    tailscale_oauth_key: "{{ lookup('env', 'TAILSCALE_OAUTH_KEY') }}"
  roles:
    - role: xanmanning.k3s
      vars:
        k3s_become: true
        k3s_server:
          disable:
            - servicelb
            - traefik
          vpn-auth: name=tailscale,joinKey={{ tailscale_oauth_key }}
        k3s_agent:
          vpn-auth: name=tailscale,joinKey={{ tailscale_oauth_key }}
