---
- name: Update netplan config
  ansible.builtin.copy:
    src: 50-cloud-init.yml
    dest: /etc/netplan/50-cloud-init.yaml

- name: Set IP
  ansible.builtin.replace:
    path: /etc/netplan/50-cloud-init.yaml
    regexp: "{ip}"
    replace: "{{ ips[inventory_hostname] + '/24' }}"

- name: Apply netplan
  command: sudo netplan apply
  async: 45
  poll: 0

- name: Update cmdline.txt file
  command: sed -i -e 's/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/' /boot/firmware/cmdline.txt
